# Generated by Django 5.1.1 on 2024-12-12 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
