# Generated by Django 5.1.1 on 2024-12-13 05:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('companyid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('companyname', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('website', models.CharField(max_length=128)),
                ('address', models.CharField(max_length=200)),
                ('registration_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
