# Generated by Django 5.1.1 on 2024-12-13 05:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('jobid', models.AutoField(primary_key=True, serialize=False)),
                ('job_experience', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=100)),
                ('open_position', models.CharField(max_length=100)),
                ('job_timing', models.CharField(max_length=100)),
                ('job_package', models.CharField(max_length=100)),
                ('job_requirement', models.CharField(max_length=225)),
                ('job_skill', models.CharField(max_length=200)),
                ('job_title', models.CharField(max_length=200)),
                ('job_desc', models.CharField(max_length=200)),
                ('job_location', models.CharField(max_length=200)),
                ('posting_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.company')),
            ],
        ),
    ]
