# Generated by Django 5.1.1 on 2024-12-13 06:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_jobpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('applicationid', models.AutoField(primary_key=True, serialize=False)),
                ('application_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('JobPost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.jobpost')),
                ('UserProfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.userprofile')),
            ],
        ),
    ]
