# Generated by Django 5.1.1 on 2025-01-09 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0009_company_jobpost_application'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='company',
        ),
        migrations.DeleteModel(
            name='Application',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='JobPost',
        ),
    ]
