# Generated by Django 5.1.1 on 2025-01-09 04:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0010_remove_jobpost_company_delete_application_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('companyid', models.AutoField(primary_key=True, serialize=False)),
                ('companyname', models.CharField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('company_email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('registration_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('jobid', models.AutoField(primary_key=True, serialize=False)),
                ('job_experience', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=100)),
                ('website', models.CharField(max_length=128)),
                ('open_position', models.CharField(max_length=100)),
                ('job_type', models.CharField(max_length=100)),
                ('job_package', models.CharField(max_length=100)),
                ('job_requirement', models.CharField(max_length=225)),
                ('job_skill', models.CharField(max_length=200)),
                ('job_title', models.CharField(max_length=200)),
                ('job_desc', models.CharField(max_length=200)),
                ('job_location', models.CharField(max_length=200)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('posting_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.company')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('applicationid', models.AutoField(primary_key=True, serialize=False)),
                ('application_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('UserProfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.userprofile')),
                ('JobPost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.jobpost')),
            ],
        ),
    ]
